---
  - name: Configure Slave List
    template: 
      src: slaves
      dest: "{{ spark_extract_location }}/conf/slaves"

  - name: Start Master
    shell: "{{ spark_extract_location }}/sbin/start-master.sh"

  #- name: Start Slaves
  #  shell: "{{ spark_extract_location }}/sbin/start-slaves.sh"